name: CI

on:
  push:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2022 ]
        java: [ 8, 11, 17, 19, 20-ea ]
      fail-fast: false
      max-parallel: 32
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Test with Maven
        run: ./mvnw -V --no-transfer-progress -Pgen-code-cov '-P!gen-sign' -DperformRelease clean package
      - name: Upload coverage to Codecov
        # https://github.com/marketplace/actions/codecov
        uses: codecov/codecov-action@v3
        with:
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
